#!/bin/bash

COMMAND=$1

if [ $COMMAND == "build" ]; then
    docker build -f Dockerfile -t kws . --progress=plain
fi

if [ $COMMAND == "test" ]; then
    curl --include \
        --no-buffer \
        --header "Connection: Upgrade" \
        --header "Upgrade: websocket" \
        --header "Host: localhost:8801" \
        --header "Origin: http://localhost:8801" \
        --header "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" \
        --header "Sec-WebSocket-Version: 13" \
        http://localhost:8801/ws
fi

